// examples/react-frontend/src/islands/ExampleIsland.jsx
import { useState } from 'react';

export default function ExampleIsland({
  message = 'Reactive Client State Hydrated',
  runtime = 'RoadRunner',
  timestamp = '',
}) {
  const [count, setCount] = useState(0);

  return (
    <div style={{
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: '1rem',
      background: 'rgba(18, 18, 22, 0.8)',
      border: '1px solid rgba(255, 255, 255, 0.08)',
      borderRadius: '12px',
      padding: '1.25rem 1.5rem',
      fontFamily: 'system-ui, -apple-system, sans-serif',
      textAlign: 'left',
    }}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.35rem' }}>
        <div style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: '0.4rem',
          fontSize: '0.725rem',
          fontFamily: 'monospace',
          color: '#60A5FA',
          fontWeight: 600,
          letterSpacing: '0.03em',
        }}>
          <span style={{
            width: '6px',
            height: '6px',
            borderRadius: '50%',
            background: '#60A5FA',
            boxShadow: '0 0 8px rgba(96, 165, 250, 0.6)',
          }} />
          <span>React 19 Island</span>
        </div>
        <p style={{ fontSize: '0.95rem', fontWeight: 600, color: '#FFFFFF', margin: 0 }}>{message}</p>
        <span style={{ fontSize: '0.75rem', color: '#8E8E98', fontFamily: 'monospace' }}>
          Passed Props: runtime={runtime} &bull; rendered={timestamp || 'just now'}
        </span>
      </div>

      <div style={{
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
        background: 'rgba(0, 0, 0, 0.4)',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        padding: '0.35rem 0.65rem',
        borderRadius: '8px',
      }}>
        <button
          onClick={() => setCount((prev) => prev - 1)}
          style={{
            background: 'rgba(225, 29, 99, 0.15)',
            border: '1px solid rgba(225, 29, 99, 0.3)',
            color: '#FFB2BF',
            width: '28px',
            height: '28px',
            borderRadius: '6px',
            fontWeight: 700,
            fontSize: '1.1rem',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
          aria-label="Decrement counter"
        >
          -
        </button>
        <span style={{
          fontFamily: 'monospace',
          fontSize: '1.1rem',
          fontWeight: 700,
          color: '#FFFFFF',
          minWidth: '28px',
          textAlign: 'center',
        }}>
          {count}
        </span>
        <button
          onClick={() => setCount((prev) => prev + 1)}
          style={{
            background: 'rgba(225, 29, 99, 0.15)',
            border: '1px solid rgba(225, 29, 99, 0.3)',
            color: '#FFB2BF',
            width: '28px',
            height: '28px',
            borderRadius: '6px',
            fontWeight: 700,
            fontSize: '1.1rem',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
          aria-label="Increment counter"
        >
          +
        </button>
      </div>
    </div>
  );
}

// frontend/src/islands/ExampleIsland.vue
<script setup>
import { ref } from 'vue'

const props = defineProps({
  message: {
    type: String,
    default: 'Reactive Client State Hydrated',
  },
  runtime: {
    type: String,
    default: 'RoadRunner',
  },
  timestamp: {
    type: String,
    default: '',
  },
})

const count = ref(0)
const increment = () => count.value++
const decrement = () => count.value--
</script>

<template>
  <div class="island-card">
    <div class="island-info">
      <div class="island-badge">
        <span class="status-dot"></span>
        <span>Vue 3 Island</span>
      </div>
      <p class="island-message">{{ message }}</p>
      <span class="island-meta">Passed Props: runtime={{ runtime }} &bull; rendered={{ timestamp || 'just now' }}</span>
    </div>

    <div class="counter-widget">
      <button @click="decrement" class="btn-counter" aria-label="Decrement counter">-</button>
      <span class="counter-val">{{ count }}</span>
      <button @click="increment" class="btn-counter" aria-label="Increment counter">+</button>
    </div>
  </div>
</template>

<style scoped>
.island-card {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  gap: 1rem;
  background: rgba(18, 18, 22, 0.8);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 12px;
  padding: 1.25rem 1.5rem;
  font-family: system-ui, -apple-system, sans-serif;
  text-align: left;
}

.island-info {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
}

.island-badge {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  font-size: 0.725rem;
  font-family: monospace;
  color: #4ADE80;
  font-weight: 600;
  letter-spacing: 0.03em;
}

.status-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: #4ADE80;
  box-shadow: 0 0 8px rgba(74, 222, 128, 0.6);
}

.island-message {
  font-size: 0.95rem;
  font-weight: 600;
  color: #FFFFFF;
}

.island-meta {
  font-size: 0.75rem;
  color: #8E8E98;
  font-family: monospace;
}

.counter-widget {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  background: rgba(0, 0, 0, 0.4);
  border: 1px solid rgba(255, 255, 255, 0.1);
  padding: 0.35rem 0.65rem;
  border-radius: 8px;
}

.btn-counter {
  background: rgba(225, 29, 99, 0.15);
  border: 1px solid rgba(225, 29, 99, 0.3);
  color: #FFB2BF;
  width: 28px;
  height: 28px;
  border-radius: 6px;
  font-weight: 700;
  font-size: 1.1rem;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.15s ease;
}

.btn-counter:hover {
  background: rgba(225, 29, 99, 0.3);
  border-color: rgba(225, 29, 99, 0.6);
  color: #FFFFFF;
}

.counter-val {
  font-family: monospace;
  font-size: 1.1rem;
  font-weight: 700;
  color: #FFFFFF;
  min-width: 28px;
  text-align: center;
}
</style>
